config/routes.rb
Rails.application.routes.draw do
  
  
	get 'pages/static_lp'
	get 'pages/secret_page'
	get 'pages/admin_interface'
	get 'pages/home_page'
	root 'pages#landing_page'
	#root to: 'home#index'

	devise_for :admins
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :charges
	
	devise_for :users, controllers: {
	omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' 
	}
	
	scope '/admin' do
		resources :users
	end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]


         #before_action :authenticate_user!

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
  def self.from_facebook(auth)

    where(facebook_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.skip_confirmation!
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def facebook
    
    @user = User.from_facebook(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      session['devse.facebook'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    @user = User.new
  end

  # POST /resource
  def create
    super

    User.create(users_params)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    attrb = [:first_name,:last_name,:age, :phone, :profession, :nationality, :weight, :belt]
    devise_parameter_sanitizer.permit :sign_up, keys: attrb
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
    def users_params
      params.require(:user).permit(:first_name,:last_name, :age, :phone, :profession, :nationality, :weight, :belt)
    end
    def update_resource(resource, params)
      resource.update_without_password(params)
    end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!

  def index

  end

  def new

    @user_new = User.new

  end

  def create
    User.create(
      first_name: params[:user][:first_name],
      last_name: params[:user][:last_name],
      email: params[:user][:email],
      phone: params[:user][:phone],
      nationality: params[:user][:nationality],
      weight: params[:user][:weight],
      belt: params[:user][:belt],
      profession: params[:user][:profession],
      password: params[:user][:password],
      age: params[:user][:age]
      )
    redirect_to pages_admin_interface_path
  end

  def edit
    @user_to_edit = User.find(params[:id])

    @user_number = User.find(params[:id]).id
    @user_age = User.find(params[:id]).age
    @user_phone = User.find(params[:id]).phone
    @user_weight = User.find(params[:id]).weight
    @user_job = User.find(params[:id]).profession
    @user_email = User.find(params[:id]).email
    @user_first_name = User.find(params[:id]).first_name
    @user_last_name = User.find(params[:id]).last_name

  end

  def update
    @user_to_edit = User.find(params[:id])
    @user_to_edit.update(
      first_name: params[:user][:first_name],
      belt: params[:user][:belt]
      )
    redirect_to pages_admin_interface_path
  end

  

 

  def destroy

   @user_to_edit = User.find(params[:id])
   @user_to_edit.destroy
   redirect_to pages_admin_interface_path

  end

  private

  def authorize_user_crud
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

	def name_nil(value)
		if value == nil || value == ""
			return "Non renseigné"
		else
			return value
		end	
	end
end

app/views/users/edit.html.erb
<div class="div-edit-user-all">
	<div class="div-edit-user-title">
		<h1>ADMINISTRATEUR </h1>
 		<h2>Gestion des Utilisateurs</h2>
	</div>
	<div class="div-edit-user-body">	
		<div class="div-edit-user-body-number">
			Utilisateur N°<%= @user_number %>
		</div>
		<div class="div-edit-user-body-info">
     
        		<div class="div-edit-user-infos-title">
					<div>Prénom: </div>
					<div>Nom:</div>
					<div>Email:</div>
					<div>Age:</div>
					<div>Téléphone:</div>
					<div>Poids:</div>
					<div>Profession:</div>  
		        </div>
		        <div class="div-edit-user-infos-title-bis">
			    	<div> <%= name_nil(@user_first_name) %></div>
			    	<div> <%= name_nil(@user_last_name) %></div>
			    	<div> <%= name_nil(@user_email) %></div>
					<div> <%= name_nil(@user_age) %> ans </div>
					<div> <%= name_nil(@user_phone) %></div>
					<div> <%= name_nil(@user_weight) %> Kg.</div>
					<div> <%= name_nil(@user_job) %></div>
		        </div>
		</div>
		<div class="div-edit-user-body-main">		
			<div class="div-edit-user-body-edit">
				<p>Informations Modifiables: </p>
				<div class="div-select">
				<%= form_for @user_to_edit do |f| %>
					<div class="div-spe">
						Ceinture
					</div>
						<select id="user_time_zone" name="user[belt]" class="form-control">
						  <option value="Blanche">Blanche</option>
						  <option value="Bleue">Bleue</option>
						  <option value="Violette">Violette</option>
						  <option value="Marron">Marron</option>
						  <option value="Noire">Noire</option>
						</select>
						<div class="div-spe">			
							<%= f.submit "Modifier" %>
						</div>
					</div>
				<% end %>
			</div>
			<div class="div-edit-user-body-buttons">
				<div class="div-spe-button">
				<%= link_to "Encaisser l'Utilisateur", new_charge_path, class: "btn btn-success btn-lg js-scroll-trigger"%>
				</div>
				<div class="div-spe-button">
					<%= link_to "Supprimer l'Utilisateur", user_path(@user_to_edit), method: :delete, class: "btn btn-danger btn-lg js-scroll-trigger", :data => {:confirm => 'Etes-vous certain ?'}%>
				</div>				
			</div>
		</div>
		
	</div>
	<div class="div-edit-user-footer">
		<%= link_to "Retour", :back, class: "btn btn-default btn-block" %>
	</div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="div-admin-header">
	<div>
	<h1>ADMINISTRATEUR </h1>

 <h2>Gestion des Utilisateurs</h2>

 
</div>
	<div>
		<%= form_for @user_new, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
		
  <div class="form-group input-group">
    <div class="input-group-prepend">
        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
     </div>
     <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control", placeholder: "First name" %>
    </div> <!-- form-group// -->
    <div class="form-group input-group">
    <div class="input-group-prepend">
        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
     </div>
     <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control", placeholder: "Last name" %>
    </div> <!-- form-group// -->
     <div class="form-group input-group">
    <div class="input-group-prepend">
        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
     </div>
     <%= f.text_field :age, autofocus: true, autocomplete: "age", class: "form-control", placeholder: "Age" %>
    </div> <!-- form-group// -->
    <div class="form-group input-group">
    <div class="input-group-prepend">
        <span class="input-group-text"> <i class="fa fa-weight"></i> </span>
     </div>
     <%= f.text_field :weight, autofocus: true, autocomplete: "weight", class: "form-control", placeholder: "Weight" %>
    </div> <!-- form-group// -->
    <div class="form-group input-group">
      <div class="input-group-prepend">
          <span class="input-group-text"> <i class="fa fa-weight"></i> </span>
       </div>
       <select id="user_time_zone" name="user[belt]" class="form-control">
                  <option value="Blanche">Blanche</option>
                  <option value="Bleue">Bleue</option>
                  <option value="Violette">Violette</option>
                  <option value="Marron">Marron</option>
                  <option value="Noire">Noire</option>
                </select>
      </div> 
    <div class="form-group input-group">
      <div class="input-group-prepend">
        <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
     </div>
       <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "Email" %>
    </div> <!-- form-group// -->
    <div class="form-group input-group">
      <div class="input-group-prepend">
        <span class="input-group-text"> <i class="fa fa-phone"></i> </span>
    </div>
      <%= f.text_field :phone, autofocus: true, autocomplete: "phone", class: "form-control", placeholder: "Phone" %>
    </div> <!-- form-group// -->
    <div class="form-group input-group">
      <div class="input-group-prepend">
        <span class="input-group-text"> <i class="fa fa-building"></i> </span>
    </div>
    <%= f.text_field :profession, autofocus: true, autocomplete: "profession", class: "form-control", placeholder: "Profession" %>
  </div> <!-- form-group end.// -->
    <div class="form-group input-group">
      <div class="input-group-prepend">
        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
    </div>
        
    <%= f.password_field :password, autocomplete: "new-password",  class: "form-control", placeholder: "Create password (6 char. min)" %>
    </div> <!-- form-group// -->
    <div class="form-group input-group">
      <div class="input-group-prepend">
        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
    </div>
        <%= f.password_field :password_confirmation, autocomplete: "new-password",  class: "form-control", placeholder: "repeat password" %>   
     </div> <!-- form-group// -->                                      
    <div class="form-group">
      <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
    </div> <!-- form-group// -->      
                                                                     
<% end %>

		<p>
		<a href="<%= root_path%>">Lien Home</a>
		</p>
	</div>
	
</div>
<hr>
<%= link_to "Cancel", :back, class: "btn btn-default btn-block" %>