config/routes.rb
Rails.application.routes.draw do
  
  
	get 'pages/static_lp'
	get 'pages/secret_page'
	get 'pages/admin_interface'
	get 'pages/home_page'
	root 'pages#landing_page'
	#root to: 'home#index'

	devise_for :admins
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :charges
	
	devise_for :users, controllers: {
	omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' 
	}
	
	scope '/admin' do
		resources :users
	end
  
end

app/views/pages/admin_interface.html.erb
<div class="div-admin-header">
	<div>
	<h1>ADMINISTRATEUR </h1>

 <h2>Gestion des Utilisateurs</h2>
 
</div>
<div>
	<%= link_to "Sign out", destroy_admin_session_path, method: :delete, class:"btn btn-warning btn-lg js-scroll-trigger" %>
	<%= link_to "Creer un Administrateur", new_admin_registration_path, class: "btn btn-danger btn-lg js-scroll-trigger"%>
	<%= link_to "Creer un Utilisateur", new_user_path, class: "btn btn-danger btn-lg js-scroll-trigger"%>
	
</div>
</div>

<hr>
<div class="div-admin-main-stats">
	<div class="div-admin-stats">
		<div class="div-admin-name">
			Bonjour Administrateur <%= current_admin.first_name %> <%= current_admin.last_name %>.
		</div>

		<div class="div-admin-stats-data">
			Vous avez <%= @users_number %> Utilisateurs inscrits sur votre site.
		</div>

		<div class="div-admin-stats-data">
			Vous avez <%= @users_no_paid %> Utilisateurs qui n'ont pas réglé la cotisation
		</div>
	</div>
	<div class="div-admin-stats-bis">
		<div class="div-admin-stats-1">
			<input type="text" id="form-control-1" class="form-control" placeholder="User Email" aria-label="Recipient's username" aria-describedby="button-addon2">
			<input type="text" id="form-control-1" class="form-control" placeholder="Montant" aria-label="Recipient's username" aria-describedby="button-addon2">
			
		</div>
		<div class="div-admin-stats-1">
			<%= link_to "Encaisser un Utilisateur", new_charge_path, class: "btn btn-success btn-lg js-scroll-trigger"%>
		</div>
	</div>
</div>
<div class="div-searsh-bar">
	<h4>Recherche d'Utilisateurs:</h4>
	<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="button-addon2">
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="button" id="button-addon2">Go</button>
  </div>
</div>

</div>

<div class="div-main">
<div class="div-admin-table">
	<div class="div-admin-table-bis-4"> Action</div>
	<div class="div-admin-table-1-bis"> ID</div>
	<div class="div-admin-table-1-long"> Prénom</div>
	<div class="div-admin-table-1-long"> Nom</div>
	<div class="div-admin-table-1-long"> Email</div>
	<div class="div-admin-table-1"> Phone</div>
	<div class="div-admin-table-bis-3"> Poids</div>
	<div class="div-admin-table-bis-3"> Ceinture</div>
	<div class="div-admin-table-1"> Abonnement</div>
	<div class="div-admin-table-bis-2"> Droits</div>
</div>

<% @users.each do |v| %>
<div class="div-admin-table-2">
			<div class="div-admin-table-bis-4"> 
				<%= link_to "Modifier", edit_user_path(v.id), class: "btn btn-primary btn-sm js-scroll-trigger"%>
     </div>

			<div class="div-admin-table-1-bis"> <%= v.id %> </div>
			<div class="div-admin-table-1-long"> <%= if v.first_name != nil; v.first_name.titleize end%></div>
			<div class="div-admin-table-1-long"> <%= if v.last_name != nil; v.last_name.titleize end %></div>
			<div class="div-admin-table-1-long"> <%= v.email %></div>
			<div class="div-admin-table-1"> <%= v.phone %></div>
			<div class="div-admin-table-bis-3"> <%= v.weight %></div>
			<div class="div-admin-table-bis-3"> <%= if v.belt != nil; v.belt.titleize end %></div>
			<div class="div-admin-table-1"> <%= paying_code(v.subscription) %></div>
			<div class="div-admin-table-bis-2"> <%= rights_code(v.admin_rights) %></div>

</div>
<% end %>
</div>

app/views/pages/secret_page.html.erb
<% if current_user.first_name == nil || current_user.last_name == nil || current_user.age == nil || current_user.profession == nil || current_user.weight == nil || current_user.phone == nil%>
<%= link_to "PROFIL IMCOMPLET", edit_user_registration_path, class: "btn btn-secondary btn-block" %>
<% end %>

<div class="div-container-global">
  
    <div class="div-container-title">
        <h1>Bienvenue <%= current_user.first_name %> <%= current_user.last_name %></h1>
    </div>
    <div class="div-container-body">

      <div class="div-container-belt", style="background-color: 
        <% if current_user.belt == "Blanche" %> 
          white
        <% elsif current_user.belt == "Bleue" %> 
          #243dcc
        <% elsif current_user.belt == "Violette" %> 
          #663096
        <% elsif current_user.belt == "Marron" %> 
          #4d0000 
        <% elsif current_user.belt == "Noire" %> 
          #292929
       <% end%> 
       ;">
     
      </div>

    <div class="div-container-body-infos">
      <div class="div-container-img">
        <img src="//placehold.it/100" class="avatar img-circle" alt="avatar">
      </div>
      <div class="div-container-body-infos-sub">
        <div class="div-infos-title">
          <div>Age:</div>
          <div>Poids:</div>
          <div>Prof:</div>
          <div>Email:</div>
          <div>Ceinture:</div>
          <div>Téléphone:</div>      
        </div>
        <div>
          <div> <%= current_user.age %></div>
          <div> <%= current_user.weight %> </div>
          <div> <%= current_user.profession %></div>
          <div> <%= current_user.email %></div>
          <div> <%= current_user.belt %>  </div>
          <div> <%= current_user.phone %></div>
        </div>
      </div>
    
    </div>

  <div class="div-container-foot">
    <div class="div-container-foot-sub">
      <%= link_to "Me Déconnecter", destroy_user_session_path, method: :delete, class: "btn btn-danger", style: "width: 300px;" %>
    </div>
    <div class="div-container-foot-sub">
      <%= link_to "Modifier mon Profil", edit_user_registration_path, class: "btn btn-default" %>
    </div>
    <div class="div-container-foot-sub">
       <%= link_to "Annuler", :back, class: "btn btn-default" %>
    </div>
  </div>

</div> 